// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type CoreBankingActuaryInfo struct {
	ID           int64     `json:"id"`
	EmployeeID   int64     `json:"employee_id"`
	ActuaryType  string    `json:"actuary_type"`
	Limit        string    `json:"limit"`
	UsedLimit    string    `json:"used_limit"`
	NeedApproval bool      `json:"need_approval"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type CoreBankingDelatnost struct {
	ID     int64  `json:"id"`
	Sifra  string `json:"sifra"`
	Naziv  string `json:"naziv"`
	Grana  string `json:"grana"`
	Sektor string `json:"sektor"`
}

type CoreBankingFirma struct {
	ID           int64  `json:"id"`
	NazivFirme   string `json:"naziv_firme"`
	MaticniBroj  string `json:"maticni_broj"`
	PoreskiBroj  string `json:"poreski_broj"`
	IDDelatnosti int64  `json:"id_delatnosti"`
	Adresa       string `json:"adresa"`
	VlasnikID    int64  `json:"vlasnik_id"`
}

type CoreBankingKartica struct {
	ID                         int64          `json:"id"`
	BrojKartice                string         `json:"broj_kartice"`
	VrstaKartice               string         `json:"vrsta_kartice"`
	DatumKreiranja             time.Time      `json:"datum_kreiranja"`
	DatumIsteka                time.Time      `json:"datum_isteka"`
	RacunID                    int64          `json:"racun_id"`
	CvvKod                     string         `json:"cvv_kod"`
	LimitKartice               string         `json:"limit_kartice"`
	Status                     string         `json:"status"`
	TipKartice                 string         `json:"tip_kartice"`
	ProvizijaProcenat          sql.NullString `json:"provizija_procenat"`
	KonverzionaNaknadaProcenat sql.NullString `json:"konverziona_naknada_procenat"`
}

type CoreBankingKredit struct {
	ID                    int64         `json:"id"`
	BrojKredita           string        `json:"broj_kredita"`
	KreditniZahtevID      sql.NullInt64 `json:"kreditni_zahtev_id"`
	BrojRacuna            string        `json:"broj_racuna"`
	VlasnikID             int64         `json:"vlasnik_id"`
	VrstaKredita          string        `json:"vrsta_kredita"`
	TipKamate             string        `json:"tip_kamate"`
	IznosKredita          string        `json:"iznos_kredita"`
	PeriodOtplate         int32         `json:"period_otplate"`
	NominalnaKamatnaStopa string        `json:"nominalna_kamatna_stopa"`
	EfektivnaKamatnaStopa string        `json:"efektivna_kamatna_stopa"`
	IznosMesecneRate      string        `json:"iznos_mesecne_rate"`
	PreostaloDugovanje    string        `json:"preostalo_dugovanje"`
	Valuta                string        `json:"valuta"`
	DatumUgovaranja       time.Time     `json:"datum_ugovaranja"`
	DatumIsplate          sql.NullTime  `json:"datum_isplate"`
	DatumSledeceRate      sql.NullTime  `json:"datum_sledece_rate"`
	Status                string        `json:"status"`
	CreatedAt             time.Time     `json:"created_at"`
}

type CoreBankingKreditniZahtev struct {
	ID                int64          `json:"id"`
	VlasnikID         int64          `json:"vlasnik_id"`
	VrstaKredita      string         `json:"vrsta_kredita"`
	TipKamate         string         `json:"tip_kamate"`
	IznosKredita      string         `json:"iznos_kredita"`
	Valuta            string         `json:"valuta"`
	RokOtplate        int32          `json:"rok_otplate"`
	SvrhaKredita      sql.NullString `json:"svrha_kredita"`
	IznosMesecnePlate string         `json:"iznos_mesecne_plate"`
	StatusZaposlenja  string         `json:"status_zaposlenja"`
	PeriodZaposlenja  int32          `json:"period_zaposlenja"`
	KontaktTelefon    string         `json:"kontakt_telefon"`
	BrojRacuna        string         `json:"broj_racuna"`
	Status            string         `json:"status"`
	DatumPodnosenja   time.Time      `json:"datum_podnosenja"`
}

type CoreBankingOvlascenoLice struct {
	ID            int64          `json:"id"`
	KarticaID     int64          `json:"kartica_id"`
	Ime           sql.NullString `json:"ime"`
	Prezime       sql.NullString `json:"prezime"`
	Pol           sql.NullString `json:"pol"`
	EmailAdresa   sql.NullString `json:"email_adresa"`
	BrojTelefona  sql.NullString `json:"broj_telefona"`
	Adresa        sql.NullString `json:"adresa"`
	DatumRodjenja sql.NullInt64  `json:"datum_rodjenja"`
}

type CoreBankingPaymentIntent struct {
	ID                 int64          `json:"id"`
	IdempotencyKey     uuid.UUID      `json:"idempotency_key"`
	BrojNaloga         string         `json:"broj_naloga"`
	TipTransakcije     string         `json:"tip_transakcije"`
	RacunPlatiocaID    int64          `json:"racun_platioca_id"`
	BrojRacunaPlatioca string         `json:"broj_racuna_platioca"`
	RacunPrimaocaID    sql.NullInt64  `json:"racun_primaoca_id"`
	BrojRacunaPrimaoca string         `json:"broj_racuna_primaoca"`
	NazivPrimaoca      string         `json:"naziv_primaoca"`
	Iznos              string         `json:"iznos"`
	KrajnjiIznos       sql.NullString `json:"krajnji_iznos"`
	Provizija          string         `json:"provizija"`
	Valuta             string         `json:"valuta"`
	SifraPlacanja      sql.NullString `json:"sifra_placanja"`
	PozivNaBroj        sql.NullString `json:"poziv_na_broj"`
	SvrhaPlacanja      sql.NullString `json:"svrha_placanja"`
	Status             string         `json:"status"`
	PendingActionID    sql.NullInt64  `json:"pending_action_id"`
	InitiatedByUserID  int64          `json:"initiated_by_user_id"`
	CreatedAt          time.Time      `json:"created_at"`
	VerifiedAt         sql.NullTime   `json:"verified_at"`
	ExecutedAt         sql.NullTime   `json:"executed_at"`
	FailedReason       sql.NullString `json:"failed_reason"`
	Kurs               sql.NullString `json:"kurs"`
	ValutaPrimaoca     sql.NullString `json:"valuta_primaoca"`
}

type CoreBankingPaymentRecipient struct {
	ID         int64     `json:"id"`
	VlasnikID  int64     `json:"vlasnik_id"`
	Naziv      string    `json:"naziv"`
	BrojRacuna string    `json:"broj_racuna"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type CoreBankingPendingAction struct {
	ID               int64           `json:"id"`
	VlasnikID        int64           `json:"vlasnik_id"`
	RacunID          int64           `json:"racun_id"`
	ActionType       string          `json:"action_type"`
	ParamsJson       json.RawMessage `json:"params_json"`
	Opis             string          `json:"opis"`
	Status           string          `json:"status"`
	VerificationCode sql.NullString  `json:"verification_code"`
	CodeExpiresAt    sql.NullTime    `json:"code_expires_at"`
	Attempts         int32           `json:"attempts"`
	CreatedAt        time.Time       `json:"created_at"`
}

type CoreBankingRacun struct {
	ID                  int64          `json:"id"`
	BrojRacuna          string         `json:"broj_racuna"`
	IDZaposlenog        int64          `json:"id_zaposlenog"`
	IDVlasnika          int64          `json:"id_vlasnika"`
	IDFirme             sql.NullInt64  `json:"id_firme"`
	IDValute            int64          `json:"id_valute"`
	KategorijaRacuna    string         `json:"kategorija_racuna"`
	VrstaRacuna         string         `json:"vrsta_racuna"`
	Podvrsta            sql.NullString `json:"podvrsta"`
	NazivRacuna         string         `json:"naziv_racuna"`
	StanjeRacuna        string         `json:"stanje_racuna"`
	RezervisanaSredstva string         `json:"rezervisana_sredstva"`
	DatumKreiranja      time.Time      `json:"datum_kreiranja"`
	DatumIsteka         time.Time      `json:"datum_isteka"`
	Status              string         `json:"status"`
	OdrzavanjeRacuna    sql.NullString `json:"odrzavanje_racuna"`
	DnevniLimit         sql.NullString `json:"dnevni_limit"`
	MesecniLimit        sql.NullString `json:"mesecni_limit"`
	DnevnaPotrosnja     string         `json:"dnevna_potrosnja"`
	MesecnaPotrosnja    string         `json:"mesecna_potrosnja"`
}

type CoreBankingRatum struct {
	ID                    int64        `json:"id"`
	KreditID              int64        `json:"kredit_id"`
	IznosRate             string       `json:"iznos_rate"`
	IznosKamate           string       `json:"iznos_kamate"`
	Valuta                string       `json:"valuta"`
	OcekivaniDatumDospeca time.Time    `json:"ocekivani_datum_dospeca"`
	PraviDatumDospeca     sql.NullTime `json:"pravi_datum_dospeca"`
	StatusPlacanja        string       `json:"status_placanja"`
	BrojPokusaja          int32        `json:"broj_pokusaja"`
	SledeciPokusaj        sql.NullTime `json:"sledeci_pokusaj"`
}

type CoreBankingTransakcija struct {
	ID               int64          `json:"id"`
	RacunID          int64          `json:"racun_id"`
	TipTransakcije   string         `json:"tip_transakcije"`
	Iznos            string         `json:"iznos"`
	Opis             sql.NullString `json:"opis"`
	VremeIzvrsavanja time.Time      `json:"vreme_izvrsavanja"`
	Status           string         `json:"status"`
}

type CoreBankingValutum struct {
	ID     int64  `json:"id"`
	Naziv  string `json:"naziv"`
	Oznaka string `json:"oznaka"`
	Simbol string `json:"simbol"`
	Zemlja string `json:"zemlja"`
	Status bool   `json:"status"`
}
